//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldClient.WorldWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContinentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        private decimal SurfaceAreaField;
        
        private int PopulationField;
        
        private double LifeExpectancyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GovernmentFormField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Continent {
            get {
                return this.ContinentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContinentField, value) != true)) {
                    this.ContinentField = value;
                    this.RaisePropertyChanged("Continent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal SurfaceArea {
            get {
                return this.SurfaceAreaField;
            }
            set {
                if ((this.SurfaceAreaField.Equals(value) != true)) {
                    this.SurfaceAreaField = value;
                    this.RaisePropertyChanged("SurfaceArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double LifeExpectancy {
            get {
                return this.LifeExpectancyField;
            }
            set {
                if ((this.LifeExpectancyField.Equals(value) != true)) {
                    this.LifeExpectancyField = value;
                    this.RaisePropertyChanged("LifeExpectancy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string GovernmentForm {
            get {
                return this.GovernmentFormField;
            }
            set {
                if ((object.ReferenceEquals(this.GovernmentFormField, value) != true)) {
                    this.GovernmentFormField = value;
                    this.RaisePropertyChanged("GovernmentForm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        private int PopulationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorldWS.WorldWSSoap")]
    public interface WorldWSSoap {
        
        // CODEGEN: Generating message contract since element name GetAllCountriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        WorldClient.WorldWS.GetAllCountriesResponse GetAllCountries(WorldClient.WorldWS.GetAllCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldClient.WorldWS.GetAllCountriesResponse> GetAllCountriesAsync(WorldClient.WorldWS.GetAllCountriesRequest request);
        
        // CODEGEN: Generating message contract since element name countryCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        WorldClient.WorldWS.GetCountryByCodeResponse GetCountryByCode(WorldClient.WorldWS.GetCountryByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldClient.WorldWS.GetCountryByCodeResponse> GetCountryByCodeAsync(WorldClient.WorldWS.GetCountryByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name cityName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        WorldClient.WorldWS.GetCityByNameResponse GetCityByName(WorldClient.WorldWS.GetCityByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldClient.WorldWS.GetCityByNameResponse> GetCityByNameAsync(WorldClient.WorldWS.GetCityByNameRequest request);
        
        // CODEGEN: Generating message contract since element name countryCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountry", ReplyAction="*")]
        WorldClient.WorldWS.GetCitiesByCountryResponse GetCitiesByCountry(WorldClient.WorldWS.GetCitiesByCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldClient.WorldWS.GetCitiesByCountryResponse> GetCitiesByCountryAsync(WorldClient.WorldWS.GetCitiesByCountryRequest request);
        
        // CODEGEN: Generating message contract since element name continent from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountriesByContinent", ReplyAction="*")]
        WorldClient.WorldWS.GetCountriesByContinentResponse GetCountriesByContinent(WorldClient.WorldWS.GetCountriesByContinentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountriesByContinent", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldClient.WorldWS.GetCountriesByContinentResponse> GetCountriesByContinentAsync(WorldClient.WorldWS.GetCountriesByContinentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCountries", Namespace="http://tempuri.org/", Order=0)]
        public WorldClient.WorldWS.GetAllCountriesRequestBody Body;
        
        public GetAllCountriesRequest() {
        }
        
        public GetAllCountriesRequest(WorldClient.WorldWS.GetAllCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCountriesRequestBody {
        
        public GetAllCountriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCountriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WorldClient.WorldWS.GetAllCountriesResponseBody Body;
        
        public GetAllCountriesResponse() {
        }
        
        public GetAllCountriesResponse(WorldClient.WorldWS.GetAllCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldClient.WorldWS.Country[] GetAllCountriesResult;
        
        public GetAllCountriesResponseBody() {
        }
        
        public GetAllCountriesResponseBody(WorldClient.WorldWS.Country[] GetAllCountriesResult) {
            this.GetAllCountriesResult = GetAllCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCode", Namespace="http://tempuri.org/", Order=0)]
        public WorldClient.WorldWS.GetCountryByCodeRequestBody Body;
        
        public GetCountryByCodeRequest() {
        }
        
        public GetCountryByCodeRequest(WorldClient.WorldWS.GetCountryByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetCountryByCodeRequestBody() {
        }
        
        public GetCountryByCodeRequestBody(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WorldClient.WorldWS.GetCountryByCodeResponseBody Body;
        
        public GetCountryByCodeResponse() {
        }
        
        public GetCountryByCodeResponse(WorldClient.WorldWS.GetCountryByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldClient.WorldWS.Country GetCountryByCodeResult;
        
        public GetCountryByCodeResponseBody() {
        }
        
        public GetCountryByCodeResponseBody(WorldClient.WorldWS.Country GetCountryByCodeResult) {
            this.GetCountryByCodeResult = GetCountryByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByName", Namespace="http://tempuri.org/", Order=0)]
        public WorldClient.WorldWS.GetCityByNameRequestBody Body;
        
        public GetCityByNameRequest() {
        }
        
        public GetCityByNameRequest(WorldClient.WorldWS.GetCityByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cityName;
        
        public GetCityByNameRequestBody() {
        }
        
        public GetCityByNameRequestBody(string cityName) {
            this.cityName = cityName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WorldClient.WorldWS.GetCityByNameResponseBody Body;
        
        public GetCityByNameResponse() {
        }
        
        public GetCityByNameResponse(WorldClient.WorldWS.GetCityByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldClient.WorldWS.City GetCityByNameResult;
        
        public GetCityByNameResponseBody() {
        }
        
        public GetCityByNameResponseBody(WorldClient.WorldWS.City GetCityByNameResult) {
            this.GetCityByNameResult = GetCityByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountry", Namespace="http://tempuri.org/", Order=0)]
        public WorldClient.WorldWS.GetCitiesByCountryRequestBody Body;
        
        public GetCitiesByCountryRequest() {
        }
        
        public GetCitiesByCountryRequest(WorldClient.WorldWS.GetCitiesByCountryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetCitiesByCountryRequestBody() {
        }
        
        public GetCitiesByCountryRequestBody(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public WorldClient.WorldWS.GetCitiesByCountryResponseBody Body;
        
        public GetCitiesByCountryResponse() {
        }
        
        public GetCitiesByCountryResponse(WorldClient.WorldWS.GetCitiesByCountryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldClient.WorldWS.City[] GetCitiesByCountryResult;
        
        public GetCitiesByCountryResponseBody() {
        }
        
        public GetCitiesByCountryResponseBody(WorldClient.WorldWS.City[] GetCitiesByCountryResult) {
            this.GetCitiesByCountryResult = GetCitiesByCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesByContinentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesByContinent", Namespace="http://tempuri.org/", Order=0)]
        public WorldClient.WorldWS.GetCountriesByContinentRequestBody Body;
        
        public GetCountriesByContinentRequest() {
        }
        
        public GetCountriesByContinentRequest(WorldClient.WorldWS.GetCountriesByContinentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesByContinentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string continent;
        
        public GetCountriesByContinentRequestBody() {
        }
        
        public GetCountriesByContinentRequestBody(string continent) {
            this.continent = continent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesByContinentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesByContinentResponse", Namespace="http://tempuri.org/", Order=0)]
        public WorldClient.WorldWS.GetCountriesByContinentResponseBody Body;
        
        public GetCountriesByContinentResponse() {
        }
        
        public GetCountriesByContinentResponse(WorldClient.WorldWS.GetCountriesByContinentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesByContinentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldClient.WorldWS.Country[] GetCountriesByContinentResult;
        
        public GetCountriesByContinentResponseBody() {
        }
        
        public GetCountriesByContinentResponseBody(WorldClient.WorldWS.Country[] GetCountriesByContinentResult) {
            this.GetCountriesByContinentResult = GetCountriesByContinentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorldWSSoapChannel : WorldClient.WorldWS.WorldWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorldWSSoapClient : System.ServiceModel.ClientBase<WorldClient.WorldWS.WorldWSSoap>, WorldClient.WorldWS.WorldWSSoap {
        
        public WorldWSSoapClient() {
        }
        
        public WorldWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorldWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorldClient.WorldWS.GetAllCountriesResponse WorldClient.WorldWS.WorldWSSoap.GetAllCountries(WorldClient.WorldWS.GetAllCountriesRequest request) {
            return base.Channel.GetAllCountries(request);
        }
        
        public WorldClient.WorldWS.Country[] GetAllCountries() {
            WorldClient.WorldWS.GetAllCountriesRequest inValue = new WorldClient.WorldWS.GetAllCountriesRequest();
            inValue.Body = new WorldClient.WorldWS.GetAllCountriesRequestBody();
            WorldClient.WorldWS.GetAllCountriesResponse retVal = ((WorldClient.WorldWS.WorldWSSoap)(this)).GetAllCountries(inValue);
            return retVal.Body.GetAllCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldClient.WorldWS.GetAllCountriesResponse> WorldClient.WorldWS.WorldWSSoap.GetAllCountriesAsync(WorldClient.WorldWS.GetAllCountriesRequest request) {
            return base.Channel.GetAllCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldClient.WorldWS.GetAllCountriesResponse> GetAllCountriesAsync() {
            WorldClient.WorldWS.GetAllCountriesRequest inValue = new WorldClient.WorldWS.GetAllCountriesRequest();
            inValue.Body = new WorldClient.WorldWS.GetAllCountriesRequestBody();
            return ((WorldClient.WorldWS.WorldWSSoap)(this)).GetAllCountriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorldClient.WorldWS.GetCountryByCodeResponse WorldClient.WorldWS.WorldWSSoap.GetCountryByCode(WorldClient.WorldWS.GetCountryByCodeRequest request) {
            return base.Channel.GetCountryByCode(request);
        }
        
        public WorldClient.WorldWS.Country GetCountryByCode(string countryCode) {
            WorldClient.WorldWS.GetCountryByCodeRequest inValue = new WorldClient.WorldWS.GetCountryByCodeRequest();
            inValue.Body = new WorldClient.WorldWS.GetCountryByCodeRequestBody();
            inValue.Body.countryCode = countryCode;
            WorldClient.WorldWS.GetCountryByCodeResponse retVal = ((WorldClient.WorldWS.WorldWSSoap)(this)).GetCountryByCode(inValue);
            return retVal.Body.GetCountryByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldClient.WorldWS.GetCountryByCodeResponse> WorldClient.WorldWS.WorldWSSoap.GetCountryByCodeAsync(WorldClient.WorldWS.GetCountryByCodeRequest request) {
            return base.Channel.GetCountryByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldClient.WorldWS.GetCountryByCodeResponse> GetCountryByCodeAsync(string countryCode) {
            WorldClient.WorldWS.GetCountryByCodeRequest inValue = new WorldClient.WorldWS.GetCountryByCodeRequest();
            inValue.Body = new WorldClient.WorldWS.GetCountryByCodeRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((WorldClient.WorldWS.WorldWSSoap)(this)).GetCountryByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorldClient.WorldWS.GetCityByNameResponse WorldClient.WorldWS.WorldWSSoap.GetCityByName(WorldClient.WorldWS.GetCityByNameRequest request) {
            return base.Channel.GetCityByName(request);
        }
        
        public WorldClient.WorldWS.City GetCityByName(string cityName) {
            WorldClient.WorldWS.GetCityByNameRequest inValue = new WorldClient.WorldWS.GetCityByNameRequest();
            inValue.Body = new WorldClient.WorldWS.GetCityByNameRequestBody();
            inValue.Body.cityName = cityName;
            WorldClient.WorldWS.GetCityByNameResponse retVal = ((WorldClient.WorldWS.WorldWSSoap)(this)).GetCityByName(inValue);
            return retVal.Body.GetCityByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldClient.WorldWS.GetCityByNameResponse> WorldClient.WorldWS.WorldWSSoap.GetCityByNameAsync(WorldClient.WorldWS.GetCityByNameRequest request) {
            return base.Channel.GetCityByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldClient.WorldWS.GetCityByNameResponse> GetCityByNameAsync(string cityName) {
            WorldClient.WorldWS.GetCityByNameRequest inValue = new WorldClient.WorldWS.GetCityByNameRequest();
            inValue.Body = new WorldClient.WorldWS.GetCityByNameRequestBody();
            inValue.Body.cityName = cityName;
            return ((WorldClient.WorldWS.WorldWSSoap)(this)).GetCityByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorldClient.WorldWS.GetCitiesByCountryResponse WorldClient.WorldWS.WorldWSSoap.GetCitiesByCountry(WorldClient.WorldWS.GetCitiesByCountryRequest request) {
            return base.Channel.GetCitiesByCountry(request);
        }
        
        public WorldClient.WorldWS.City[] GetCitiesByCountry(string countryCode) {
            WorldClient.WorldWS.GetCitiesByCountryRequest inValue = new WorldClient.WorldWS.GetCitiesByCountryRequest();
            inValue.Body = new WorldClient.WorldWS.GetCitiesByCountryRequestBody();
            inValue.Body.countryCode = countryCode;
            WorldClient.WorldWS.GetCitiesByCountryResponse retVal = ((WorldClient.WorldWS.WorldWSSoap)(this)).GetCitiesByCountry(inValue);
            return retVal.Body.GetCitiesByCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldClient.WorldWS.GetCitiesByCountryResponse> WorldClient.WorldWS.WorldWSSoap.GetCitiesByCountryAsync(WorldClient.WorldWS.GetCitiesByCountryRequest request) {
            return base.Channel.GetCitiesByCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldClient.WorldWS.GetCitiesByCountryResponse> GetCitiesByCountryAsync(string countryCode) {
            WorldClient.WorldWS.GetCitiesByCountryRequest inValue = new WorldClient.WorldWS.GetCitiesByCountryRequest();
            inValue.Body = new WorldClient.WorldWS.GetCitiesByCountryRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((WorldClient.WorldWS.WorldWSSoap)(this)).GetCitiesByCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorldClient.WorldWS.GetCountriesByContinentResponse WorldClient.WorldWS.WorldWSSoap.GetCountriesByContinent(WorldClient.WorldWS.GetCountriesByContinentRequest request) {
            return base.Channel.GetCountriesByContinent(request);
        }
        
        public WorldClient.WorldWS.Country[] GetCountriesByContinent(string continent) {
            WorldClient.WorldWS.GetCountriesByContinentRequest inValue = new WorldClient.WorldWS.GetCountriesByContinentRequest();
            inValue.Body = new WorldClient.WorldWS.GetCountriesByContinentRequestBody();
            inValue.Body.continent = continent;
            WorldClient.WorldWS.GetCountriesByContinentResponse retVal = ((WorldClient.WorldWS.WorldWSSoap)(this)).GetCountriesByContinent(inValue);
            return retVal.Body.GetCountriesByContinentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldClient.WorldWS.GetCountriesByContinentResponse> WorldClient.WorldWS.WorldWSSoap.GetCountriesByContinentAsync(WorldClient.WorldWS.GetCountriesByContinentRequest request) {
            return base.Channel.GetCountriesByContinentAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldClient.WorldWS.GetCountriesByContinentResponse> GetCountriesByContinentAsync(string continent) {
            WorldClient.WorldWS.GetCountriesByContinentRequest inValue = new WorldClient.WorldWS.GetCountriesByContinentRequest();
            inValue.Body = new WorldClient.WorldWS.GetCountriesByContinentRequestBody();
            inValue.Body.continent = continent;
            return ((WorldClient.WorldWS.WorldWSSoap)(this)).GetCountriesByContinentAsync(inValue);
        }
    }
}
